Image features added
ishimwepati/One-of-my-past-projects pull request #1
Opened 2023-06-13 16:49 UTC by ishimwepati

This project has a lot functionalities :
1. Images have been used,
2. Alignement using CSS
3. div tag has been used.

2023-06-13 16:55 UTC, ishimwepati commented
Hello [@ishimwepati ] 👋 ,

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!
![unnamed](https://github.com/ishimwepati/One-of-my-past-projects/assets/14818338/d1daeaf9-abe1-4310-9bee-c24c9cfd724e)

Kindly work on the issues below to finish and pass to the next project.

2023-06-13 16:58 UTC, ishimwepati commented
kindly use a div tag as a container of the hamburger for convention, semantics, and user experience(UX) 😄

<img width="561" alt="Screenshot 2023-06-13 at 19 57 44" src="https://github.com/ishimwepati/One-of-my-past-projects/assets/14818338/faac42ff-6e77-45b6-8fe7-7e544ad52a92">

2023-06-13 17:00 UTC, ishimwepati commented
Kindly use flex property to align your header items as it helps with the flexibility of your nav items 😄

In index.html at line 38 to 128.

2023-06-13 17:01 UTC, ishimwepati commented
Please the container of this headline section should be a section tag and not a nav tag as it represents a generic standalone section of your project 😄

2023-06-13 17:03 UTC, ishimwepati commented
Optional : 

1. Make efforts in using linters in your next project
2. Apply HTML and CSS best practice

2023-06-13 17:05 UTC, ishimwepati commented
I suggest that you document well your ReadMe.md file. 😄

In

2023-06-13 17:46 UTC, Alusp requested changes
Hi @ishimwepati, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
 
![almost](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights

- [ ] Github Feaure Fairly used :green_circle: 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please ensure that you follow this [step](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) to know how to use Review Features in Github as required by the project requirement, especially inline comment and the commenting section.  GitHub's review features provide a structured and efficient workflow for conducting code reviews. Reviewers can add comments, suggest changes, approve or request changes to specific lines or sections of code. This makes the review process more focused, organized, and easily trackable, leading to faster iterations and better collaboration among team members. :slightly_smiling_face: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 10:49 UTC, ishimwepati reviewed
Hello [@ishimwepati ] 👋 ,

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

![unnamed](https://github.com/ishimwepati/One-of-my-past-projects/assets/14818338/469b5f6c-3b14-44d1-a5f8-b22edfd79733)

2023-06-14 10:49 UTC, ishimwepati commented on index.html
> +        >
Kindly use a div tag as a container of the hamburger for convention, semantics, and user experience(UX), it makes your code clean😄

2023-06-14 10:49 UTC, ishimwepati commented on index.html
>      <a
Please use flex property to align your header items as it helps with the flexibility of your nav items 😄

2023-06-14 10:54 UTC, ishimwepati reviewed
I suggest that you document well your ReadMe.md file by following the https://github.com/microverseinc/readme-template model. 😄

2023-06-14 11:04 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @ishimwepati 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Proper use of GitHub inline comments feature ✔
- Comments are phrased politely ✔
- Comments are clear and easy to understand ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 11:11 UTC, merged